### ISSUE TITLE
Unable to run project after adding this plugin (Module 'nativescript-card-stack-view' not found for element 'nativescript-card-stack-view:CardStack'.    > Cannot read property 'widget' of undefined)

### ISSUE THREAD

**Issue by vishnuchd** [ProximaTeam/nativescript-card-stack-view#2]
This is a very useful plugin, but i am facing a issue while integerating the plugin in my project, i am getting this error

```
An uncaught Exception occurred on "main" thread.
Unable to start activity ComponentInfo{org.nativescript.NativeCoreSample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > Building UI from XML. @main-page.xml:13:13
   > Module 'nativescript-card-stack-view' not found for element 'nativescript-card-stack-view:CardStack'.
   > Cannot read property 'widget' of undefined

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.NativeCoreSample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > Building UI from XML. @main-page.xml:13:13
   > Module 'nativescript-card-stack-view' not found for element 'nativescript-card-stack-view:CardStack'.
   > Cannot read property 'widget' of undefined
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > Building UI from XML. @main-page.xml:13:13
   > Module 'nativescript-card-stack-view' not found for element 'nativescript-card-stack-view:CardStack'.
   > Cannot read property 'widget' of undefined
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
	at android.app.Activity.performCreate(Activity.java:6259)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 9 more
```

i have no idea how to fix this, even the demo i downloaded is not working. 

here is my project.json
```{
  "nativescript": {
    "id": "org.nativescript.NativeCoreSample",
    "tns-ios": {
      "version": "6.4.0"
    },
    "tns-android": {
      "version": "6.4.1"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "~2.3.0",
    "nativescript-card-stack-view": "0.0.5",
    "tns-core-modules": "~6.4.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.5.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "d8bdf0799a219051f28f8abd7c258d2bf2fce6e1",
  "readme": "NativeScript Application"
}
```

**Comment by FranciZ** [comment]
Hey,

thanks for reporting. Yes the latest android SDKs require use of AndroidX library instead of the standard support libraries. Fix is on the way.

Best
